name: Trigger License Check

on:
  pull_request_target:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    uses: brcm-test/.github/.github/workflows/license-check.yml@main
    with:
      pull-request-target: true
      issue-comment: true
    secrets: inherit
